version: '2'

networks:
  teamcity:
    driver: bridge
services:
  teamcity-proxy:
    image: jwilder/nginx-proxy:latest
    ports:
     - "80:80"
     - "443:443"
    volumes:
      - '/home/docker/nginx-proxy/ssl:/etc/nginx/certs:ro'
      - '/etc/nginx/vhost.d'
      - '/usr/share/nginx/html'
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
    networks:
      - teamcity
  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    volumes_from:
      - teamcity-proxy
    volumes:
      - '/home/docker/nginx-proxy/ssl:/etc/nginx/certs:rw'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    networks:
      - teamcity
  teamcity-server:
    image: jetbrains/teamcity-server
    environment:
      VIRTUAL_PORT: 8011
      VIRTUAL_HOST: teamcity.kalastud.io
      LETSENCRYPT_HOST: teamcity.kalastud.io
      LETSENCRYPT_EMAIL: iulian.rotaru@epitech.eu
    volumes:
      - '/home/docker/teamcity-server/mysql:/var/lib/mysql:rw'
    networks:
      - teamcity